export const problemsData = [
  // ---- ARRAY ----
  { title: "Two Sum", url: "https://leetcode.com/problems/two-sum/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Best Time To Buy And Sell Stock", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Plus One", url: "https://leetcode.com/problems/plus-one/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Move Zeroes", url: "https://leetcode.com/problems/move-zeroes/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Best Time To Buy And Sell Stock II", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Running Sum Of 1d Array", url: "https://leetcode.com/problems/running-sum-of-1d-array/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Find Pivot Index", url: "https://leetcode.com/problems/find-pivot-index/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Majority Element", url: "https://leetcode.com/problems/majority-element/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Fibonacci Number", url: "https://leetcode.com/problems/fibonacci-number/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Squares Of A Sorted Array", url: "https://leetcode.com/problems/squares-of-a-sorted-array/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Pascals Triangle", url: "https://leetcode.com/problems/pascals-triangle/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Remove Duplicates From Sorted Array", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", category: "Array", difficulty: "Easy", platform: "LeetCode" },
  { title: "Merge Intervals", url: "https://leetcode.com/problems/merge-intervals/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "3Sum", url: "https://leetcode.com/problems/3sum/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Product Of Array Except Self", url: "https://leetcode.com/problems/product-of-array-except-self/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Insert Delete Getrandom O1", url: "https://leetcode.com/problems/insert-delete-getrandom-o1/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Subarray Sum Equals K", url: "https://leetcode.com/problems/subarray-sum-equals-k/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Next Permutation", url: "https://leetcode.com/problems/next-permutation/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Spiral Matrix", url: "https://leetcode.com/problems/spiral-matrix/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Container With Most Water", url: "https://leetcode.com/problems/container-with-most-water/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Rotate Image", url: "https://leetcode.com/problems/rotate-image/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Word Search", url: "https://leetcode.com/problems/word-search/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "3Sum Closest", url: "https://leetcode.com/problems/3sum-closest/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Game Of Life", url: "https://leetcode.com/problems/game-of-life/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Pairs Of Songs With Total Durations Divisible By 60", url: "https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "4Sum", url: "https://leetcode.com/problems/4sum/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Find The Duplicate Number", url: "https://leetcode.com/problems/find-the-duplicate-number/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Combination Sum", url: "https://leetcode.com/problems/combination-sum/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Jump Game II", url: "https://leetcode.com/problems/jump-game-ii/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Maximum Points You Can Obtain From Cards", url: "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Maximum Area Of A Piece Of Cake After Horizontal And Vertical Cuts", url: "https://leetcode.com/problems/maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Max Area Of Island", url: "https://leetcode.com/problems/max-area-of-island/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Find All Duplicates In An Array", url: "https://leetcode.com/problems/find-all-duplicates-in-an-array/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "K Diff Pairs In An Array", url: "https://leetcode.com/problems/k-diff-pairs-in-an-array/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Subsets", url: "https://leetcode.com/problems/subsets/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Invalid Transactions", url: "https://leetcode.com/problems/invalid-transactions/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Jump Game", url: "https://leetcode.com/problems/jump-game/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "Subarray Sums Divisible By K", url: "https://leetcode.com/problems/subarray-sums-divisible-by-k/", category: "Array", difficulty: "Medium", platform: "LeetCode" },
  { title: "First Missing Positive", url: "https://leetcode.com/problems/first-missing-positive/", category: "Array", difficulty: "Hard", platform: "LeetCode" },
  { title: "Largest Rectangle In Histogram", url: "https://leetcode.com/problems/largest-rectangle-in-histogram/", category: "Array", difficulty: "Hard", platform: "LeetCode" },
  { title: "Insert Delete Getrandom O1 Duplicates Allowed", url: "https://leetcode.com/problems/insert-delete-getrandom-o1-duplicates-allowed/", category: "Array", difficulty: "Hard", platform: "LeetCode" },
  { title: "Best Time To Buy And Sell Stock III", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/", category: "Array", difficulty: "Hard", platform: "LeetCode" },
  { title: "Max Value Of Equation", url: "https://leetcode.com/problems/max-value-of-equation/", category: "Array", difficulty: "Hard", platform: "LeetCode" },

  // ---- DYNAMIC PROGRAMMING ----
  { title: "Maximum Subarray", url: "https://leetcode.com/problems/maximum-subarray/", category: "Dynamic Programming", difficulty: "Easy", platform: "LeetCode" },
  { title: "Climbing Stairs", url: "https://leetcode.com/problems/climbing-stairs/", category: "Dynamic Programming", difficulty: "Easy", platform: "LeetCode" },
  { title: "Divisor Game", url: "https://leetcode.com/problems/divisor-game/", category: "Dynamic Programming", difficulty: "Easy", platform: "LeetCode" },
  { title: "Counting Bits", url: "https://leetcode.com/problems/counting-bits/", category: "Dynamic Programming", difficulty: "Easy", platform: "LeetCode" },
  { title: "Decode Ways", url: "https://leetcode.com/problems/decode-ways/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Word Break", url: "https://leetcode.com/problems/word-break/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Delete And Earn", url: "https://leetcode.com/problems/delete-and-earn/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Maximal Square", url: "https://leetcode.com/problems/maximal-square/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Coin Change", url: "https://leetcode.com/problems/coin-change/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Maximum Product Subarray", url: "https://leetcode.com/problems/maximum-product-subarray/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Maximum Length Of Repeated Subarray", url: "https://leetcode.com/problems/maximum-length-of-repeated-subarray/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Palindromic Substrings", url: "https://leetcode.com/problems/palindromic-substrings/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "House Robber", url: "https://leetcode.com/problems/house-robber/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Continuous Subarray Sum", url: "https://leetcode.com/problems/continuous-subarray-sum/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Knight Dialer", url: "https://leetcode.com/problems/knight-dialer/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Longest Increasing Subsequence", url: "https://leetcode.com/problems/longest-increasing-subsequence/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Unique Paths", url: "https://leetcode.com/problems/unique-paths/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Count Square Submatrices With All Ones", url: "https://leetcode.com/problems/count-square-submatrices-with-all-ones/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Range Sum Query 2D Immutable", url: "https://leetcode.com/problems/range-sum-query-2d-immutable/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Longest Arithmetic Subsequence", url: "https://leetcode.com/problems/longest-arithmetic-subsequence/", category: "Dynamic Programming", difficulty: "Medium", platform: "LeetCode" },
  { title: "Trapping Rain Water", url: "https://leetcode.com/problems/trapping-rain-water/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Word Break II", url: "https://leetcode.com/problems/word-break-ii/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Regular Expression Matching", url: "https://leetcode.com/problems/regular-expression-matching/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Maximal Rectangle", url: "https://leetcode.com/problems/maximal-rectangle/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Longest Valid Parentheses", url: "https://leetcode.com/problems/longest-valid-parentheses/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Edit Distance", url: "https://leetcode.com/problems/edit-distance/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Minimum Difficulty Of A Job Schedule", url: "https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Frog Jump", url: "https://leetcode.com/problems/frog-jump/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Best Time To Buy And Sell Stock IV", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Burst Balloons", url: "https://leetcode.com/problems/burst-balloons/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Minimum Cost To Merge Stones", url: "https://leetcode.com/problems/minimum-cost-to-merge-stones/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Minimum Insertion Steps To Make A String Palindrome", url: "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Super Egg Drop", url: "https://leetcode.com/problems/super-egg-drop/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Count Different Palindromic Subsequences", url: "https://leetcode.com/problems/count-different-palindromic-subsequences/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },
  { title: "Minimum Cost To Cut A Stick", url: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/", category: "Dynamic Programming", difficulty: "Hard", platform: "LeetCode" },

  // ---- STRINGS ----
  { title: "Add Strings", url: "https://leetcode.com/problems/add-strings/", category: "Strings", difficulty: "Easy", platform: "LeetCode" },
  { title: "Longest Common Prefix", url: "https://leetcode.com/problems/longest-common-prefix/", category: "Strings", difficulty: "Easy", platform: "LeetCode" },
  { title: "Valid Palindrome II", url: "https://leetcode.com/problems/valid-palindrome-ii/", category: "Strings", difficulty: "Easy", platform: "LeetCode" },
  { title: "Roman To Integer", url: "https://leetcode.com/problems/roman-to-integer/", category: "Strings", difficulty: "Easy", platform: "LeetCode" },
  { title: "Implement Strstr", url: "https://leetcode.com/problems/implement-strstr/", category: "Strings", difficulty: "Easy", platform: "LeetCode" },
  { title: "Longest Substring Without Repeating Characters", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", category: "Strings", difficulty: "Medium", platform: "LeetCode" },
  { title: "Minimum Remove To Make Valid Parentheses", url: "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/", category: "Strings", difficulty: "Medium", platform: "LeetCode" },
  { title: "Longest Palindromic Substring", url: "https://leetcode.com/problems/longest-palindromic-substring/", category: "Strings", difficulty: "Medium", platform: "LeetCode" },
  { title: "Group Anagrams", url: "https://leetcode.com/problems/group-anagrams/", category: "Strings", difficulty: "Medium", platform: "LeetCode" },
  { title: "Generate Parentheses", url: "https://leetcode.com/problems/generate-parentheses/", category: "Strings", difficulty: "Medium", platform: "LeetCode" },
  { title: "Basic Calculator II", url: "https://leetcode.com/problems/basic-calculator-ii/", category: "Strings", difficulty: "Medium", platform: "LeetCode" },
  { title: "Integer To Roman", url: "https://leetcode.com/problems/integer-to-roman/", category: "Strings", difficulty: "Medium", platform: "LeetCode" },
  { title: "Reverse Words In A String", url: "https://leetcode.com/problems/reverse-words-in-a-string/", category: "Strings", difficulty: "Medium", platform: "LeetCode" },
  { title: "Simplify Path", url: "https://leetcode.com/problems/simplify-path/", category: "Strings", difficulty: "Medium", platform: "LeetCode" },
  { title: "Zigzag Conversion", url: "https://leetcode.com/problems/zigzag-conversion/", category: "Strings", difficulty: "Medium", platform: "LeetCode" },
  { title: "Text Justification", url: "https://leetcode.com/problems/text-justification/", category: "Strings", difficulty: "Hard", platform: "LeetCode" },
  { title: "Integer To English Words", url: "https://leetcode.com/problems/integer-to-english-words/", category: "Strings", difficulty: "Hard", platform: "LeetCode" },
  { title: "Minimum Window Substring", url: "https://leetcode.com/problems/minimum-window-substring/", category: "Strings", difficulty: "Hard", platform: "LeetCode" },
  { title: "Valid Number", url: "https://leetcode.com/problems/valid-number/", category: "Strings", difficulty: "Hard", platform: "LeetCode" },
  { title: "Distinct Subsequences", url: "https://leetcode.com/problems/distinct-subsequences/", category: "Strings", difficulty: "Hard", platform: "LeetCode" },
  { title: "Smallest Range Covering Elements From K Lists", url: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/", category: "Strings", difficulty: "Hard", platform: "LeetCode" },
  { title: "Substring With Concatenation Of All Words", url: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/", category: "Strings", difficulty: "Hard", platform: "LeetCode" },

  // ---- MATHS ----
  { title: "Reverse Integer", url: "https://leetcode.com/problems/reverse-integer/", category: "Maths", difficulty: "Easy", platform: "LeetCode" },
  { title: "Add Binary", url: "https://leetcode.com/problems/add-binary/", category: "Maths", difficulty: "Easy", platform: "LeetCode" },
  { title: "Palindrome Number", url: "https://leetcode.com/problems/palindrome-number/", category: "Maths", difficulty: "Easy", platform: "LeetCode" },
  { title: "Minimum Moves To Equal Array Elements", url: "https://leetcode.com/problems/minimum-moves-to-equal-array-elements/", category: "Maths", difficulty: "Easy", platform: "LeetCode" },
  { title: "Happy Number", url: "https://leetcode.com/problems/happy-number/", category: "Maths", difficulty: "Easy", platform: "LeetCode" },
  { title: "Excel Sheet Column Title", url: "https://leetcode.com/problems/excel-sheet-column-title/", category: "Maths", difficulty: "Easy", platform: "LeetCode" },
  { title: "Missing Number", url: "https://leetcode.com/problems/missing-number/", category: "Maths", difficulty: "Easy", platform: "LeetCode" },
  { title: "Maximum Product Of Three Numbers", url: "https://leetcode.com/problems/maximum-product-of-three-numbers/", category: "Maths", difficulty: "Easy", platform: "LeetCode" },
  { title: "Power Of Two", url: "https://leetcode.com/problems/power-of-two/", category: "Maths", difficulty: "Easy", platform: "LeetCode" },
  { title: "Encode And Decode Tinyurl", url: "https://leetcode.com/problems/encode-and-decode-tinyurl/", category: "Maths", difficulty: "Medium", platform: "LeetCode" },
  { title: "String To Integer Atoi", url: "https://leetcode.com/problems/string-to-integer-atoi/", category: "Maths", difficulty: "Medium", platform: "LeetCode" },
  { title: "Multiply Strings", url: "https://leetcode.com/problems/multiply-strings/", category: "Maths", difficulty: "Medium", platform: "LeetCode" },
  { title: "Angle Between Hands Of A Clock", url: "https://leetcode.com/problems/angle-between-hands-of-a-clock/", category: "Maths", difficulty: "Medium", platform: "LeetCode" },
  { title: "Integer Break", url: "https://leetcode.com/problems/integer-break/", category: "Maths", difficulty: "Medium", platform: "LeetCode" },
  { title: "Valid Square", url: "https://leetcode.com/problems/valid-square/", category: "Maths", difficulty: "Medium", platform: "LeetCode" },
  { title: "The Kth Factor Of N", url: "https://leetcode.com/problems/the-kth-factor-of-n/", category: "Maths", difficulty: "Medium", platform: "LeetCode" },
  { title: "Basic Calculator", url: "https://leetcode.com/problems/basic-calculator/", category: "Maths", difficulty: "Hard", platform: "LeetCode" },
  { title: "Max Points On A Line", url: "https://leetcode.com/problems/max-points-on-a-line/", category: "Maths", difficulty: "Hard", platform: "LeetCode" },
  { title: "Permutation Sequence", url: "https://leetcode.com/problems/permutation-sequence/", category: "Maths", difficulty: "Hard", platform: "LeetCode" },
  { title: "Number Of Digit One", url: "https://leetcode.com/problems/number-of-digit-one/", category: "Maths", difficulty: "Hard", platform: "LeetCode" },

  // ---- GREEDY ----
  { title: "Task Scheduler", url: "https://leetcode.com/problems/task-scheduler/", category: "Greedy", difficulty: "Medium", platform: "LeetCode" },
  { title: "Gas Station", url: "https://leetcode.com/problems/gas-station/", category: "Greedy", difficulty: "Medium", platform: "LeetCode" },
  { title: "Minimum Deletion Cost To Avoid Repeating Letters", url: "https://leetcode.com/problems/minimum-deletion-cost-to-avoid-repeating-letters/", category: "Greedy", difficulty: "Medium", platform: "LeetCode" },
  { title: "Maximum Number Of Events That Can Be Attended", url: "https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/", category: "Greedy", difficulty: "Medium", platform: "LeetCode" },
  { title: "Minimum Deletions To Make Character Frequencies Unique", url: "https://leetcode.com/problems/minimum-deletions-to-make-character-frequencies-unique/", category: "Greedy", difficulty: "Medium", platform: "LeetCode" },
  { title: "Remove K Digits", url: "https://leetcode.com/problems/remove-k-digits/", category: "Greedy", difficulty: "Medium", platform: "LeetCode" },
  { title: "Restore The Array From Adjacent Pairs", url: "https://leetcode.com/problems/restore-the-array-from-adjacent-pairs/", category: "Greedy", difficulty: "Medium", platform: "LeetCode" },
  { title: "Non Overlapping Intervals", url: "https://leetcode.com/problems/non-overlapping-intervals/", category: "Greedy", difficulty: "Medium", platform: "LeetCode" },
  { title: "Candy", url: "https://leetcode.com/problems/candy/", category: "Greedy", difficulty: "Hard", platform: "LeetCode" },
  { title: "Minimum Number Of Taps To Open To Water A Garden", url: "https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden/", category: "Greedy", difficulty: "Hard", platform: "LeetCode" },
  { title: "Create Maximum Number", url: "https://leetcode.com/problems/create-maximum-number/", category: "Greedy", difficulty: "Hard", platform: "LeetCode" },

  // ---- DFS ----
  { title: "Letter Combinations Of A Phone Number", url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/", category: "DFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Course Schedule II", url: "https://leetcode.com/problems/course-schedule-ii/", category: "DFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Decode String", url: "https://leetcode.com/problems/decode-string/", category: "DFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Number Of Provinces", url: "https://leetcode.com/problems/number-of-provinces/", category: "DFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Clone Graph", url: "https://leetcode.com/problems/clone-graph/", category: "DFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Shortest Bridge", url: "https://leetcode.com/problems/shortest-bridge/", category: "DFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "All Paths From Source To Target", url: "https://leetcode.com/problems/all-paths-from-source-to-target/", category: "DFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Surrounded Regions", url: "https://leetcode.com/problems/surrounded-regions/", category: "DFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "House Robber III", url: "https://leetcode.com/problems/house-robber-iii/", category: "DFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Critical Connections In A Network", url: "https://leetcode.com/problems/critical-connections-in-a-network/", category: "DFS", difficulty: "Hard", platform: "LeetCode" },
  { title: "Remove Invalid Parentheses", url: "https://leetcode.com/problems/remove-invalid-parentheses/", category: "DFS", difficulty: "Hard", platform: "LeetCode" },
  { title: "Longest Increasing Path In A Matrix", url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/", category: "DFS", difficulty: "Hard", platform: "LeetCode" },
  { title: "Concatenated Words", url: "https://leetcode.com/problems/concatenated-words/", category: "DFS", difficulty: "Hard", platform: "LeetCode" },
  { title: "Making A Large Island", url: "https://leetcode.com/problems/making-a-large-island/", category: "DFS", difficulty: "Hard", platform: "LeetCode" },
  { title: "Contain Virus", url: "https://leetcode.com/problems/contain-virus/", category: "DFS", difficulty: "Hard", platform: "LeetCode" },
  { title: "24 Game", url: "https://leetcode.com/problems/24-game/", category: "DFS", difficulty: "Hard", platform: "LeetCode" },
  { title: "Remove Boxes", url: "https://leetcode.com/problems/remove-boxes/", category: "DFS", difficulty: "Hard", platform: "LeetCode" },

  // ---- TREE ----
  { title: "Diameter Of Binary Tree", url: "https://leetcode.com/problems/diameter-of-binary-tree/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Invert Binary Tree", url: "https://leetcode.com/problems/invert-binary-tree/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Subtree Of Another Tree", url: "https://leetcode.com/problems/subtree-of-another-tree/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Range Sum Of BST", url: "https://leetcode.com/problems/range-sum-of-bst/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Symmetric Tree", url: "https://leetcode.com/problems/symmetric-tree/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Convert Sorted Array To Binary Search Tree", url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Merge Two Binary Trees", url: "https://leetcode.com/problems/merge-two-binary-trees/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Maximum Depth Of Binary Tree", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Binary Tree Paths", url: "https://leetcode.com/problems/binary-tree-paths/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Same Tree", url: "https://leetcode.com/problems/same-tree/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Lowest Common Ancestor Of A Binary Search Tree", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Path Sum", url: "https://leetcode.com/problems/path-sum/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Minimum Absolute Difference In BST", url: "https://leetcode.com/problems/minimum-absolute-difference-in-bst/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Sum Of Left Leaves", url: "https://leetcode.com/problems/sum-of-left-leaves/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Balanced Binary Tree", url: "https://leetcode.com/problems/balanced-binary-tree/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Binary Tree Inorder Traversal", url: "https://leetcode.com/problems/binary-tree-inorder-traversal/", category: "Tree", difficulty: "Easy", platform: "LeetCode" },
  { title: "Count Good Nodes In Binary Tree", url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Lowest Common Ancestor Of A Binary Tree", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Binary Tree Right Side View", url: "https://leetcode.com/problems/binary-tree-right-side-view/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "All Nodes Distance K In Binary Tree", url: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Validate Binary Search Tree", url: "https://leetcode.com/problems/validate-binary-search-tree/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Binary Tree Zigzag Level Order Traversal", url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Binary Search Tree Iterator", url: "https://leetcode.com/problems/binary-search-tree-iterator/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Binary Tree Level Order Traversal", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Path Sum III", url: "https://leetcode.com/problems/path-sum-iii/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Construct Binary Tree From Preorder And Postorder Traversal", url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-postorder-traversal/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Unique Binary Search Trees", url: "https://leetcode.com/problems/unique-binary-search-trees/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Recover Binary Search Tree", url: "https://leetcode.com/problems/recover-binary-search-tree/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Populating Next Right Pointers In Each Node", url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Flatten Binary Tree To Linked List", url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Maximum Width Of Binary Tree", url: "https://leetcode.com/problems/maximum-width-of-binary-tree/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Unique Binary Search Trees II", url: "https://leetcode.com/problems/unique-binary-search-trees-ii/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Kth Smallest Element In A BST", url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Redundant Connection", url: "https://leetcode.com/problems/redundant-connection/", category: "Tree", difficulty: "Medium", platform: "LeetCode" },
  { title: "Serialize And Deserialize Binary Tree", url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", category: "Tree", difficulty: "Hard", platform: "LeetCode" },
  { title: "Binary Tree Maximum Path Sum", url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", category: "Tree", difficulty: "Hard", platform: "LeetCode" },
  { title: "Vertical Order Traversal Of A Binary Tree", url: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/", category: "Tree", difficulty: "Hard", platform: "LeetCode" },
  { title: "Binary Tree Cameras", url: "https://leetcode.com/problems/binary-tree-cameras/", category: "Tree", difficulty: "Hard", platform: "LeetCode" },
  { title: "Sum Of Distances In Tree", url: "https://leetcode.com/problems/sum-of-distances-in-tree/", category: "Tree", difficulty: "Hard", platform: "LeetCode" },
  { title: "Number Of Ways To Reconstruct A Tree", url: "https://leetcode.com/problems/number-of-ways-to-reconstruct-a-tree/", category: "Tree", difficulty: "Hard", platform: "LeetCode" },
  { title: "Redundant Connection II", url: "https://leetcode.com/problems/redundant-connection-ii/", category: "Tree", difficulty: "Hard", platform: "LeetCode" },

  // ---- HASH TABLE ----
  { title: "Verifying An Alien Dictionary", url: "https://leetcode.com/problems/verifying-an-alien-dictionary/", category: "Hash Table", difficulty: "Easy", platform: "LeetCode" },
  { title: "Design Hashmap", url: "https://leetcode.com/problems/design-hashmap/", category: "Hash Table", difficulty: "Easy", platform: "LeetCode" },
  { title: "Top K Frequent Elements", url: "https://leetcode.com/problems/top-k-frequent-elements/", category: "Hash Table", difficulty: "Medium", platform: "LeetCode" },
  { title: "Design Twitter", url: "https://leetcode.com/problems/design-twitter/", category: "Hash Table", difficulty: "Medium", platform: "LeetCode" },

  // ---- BINARY SEARCH ----
  { title: "Sqrtx", url: "https://leetcode.com/problems/sqrtx/", category: "Binary Search", difficulty: "Easy", platform: "LeetCode" },
  { title: "Binary Search", url: "https://leetcode.com/problems/binary-search/", category: "Binary Search", difficulty: "Easy", platform: "LeetCode" },
  { title: "Count Negative Numbers In A Sorted Matrix", url: "https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/", category: "Binary Search", difficulty: "Easy", platform: "LeetCode" },
  { title: "Peak Index In A Mountain Array", url: "https://leetcode.com/problems/peak-index-in-a-mountain-array/", category: "Binary Search", difficulty: "Easy", platform: "LeetCode" },
  { title: "Time Based Key Value Store", url: "https://leetcode.com/problems/time-based-key-value-store/", category: "Binary Search", difficulty: "Medium", platform: "LeetCode" },
  { title: "Search In Rotated Sorted Array", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/", category: "Binary Search", difficulty: "Medium", platform: "LeetCode" },
  { title: "Powx N", url: "https://leetcode.com/problems/powx-n/", category: "Binary Search", difficulty: "Medium", platform: "LeetCode" },
  { title: "Find First And Last Position Of Element In Sorted Array", url: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", category: "Binary Search", difficulty: "Medium", platform: "LeetCode" },
  { title: "Find Peak Element", url: "https://leetcode.com/problems/find-peak-element/", category: "Binary Search", difficulty: "Medium", platform: "LeetCode" },
  { title: "Search A 2D Matrix", url: "https://leetcode.com/problems/search-a-2d-matrix/", category: "Binary Search", difficulty: "Medium", platform: "LeetCode" },
  { title: "Divide Two Integers", url: "https://leetcode.com/problems/divide-two-integers/", category: "Binary Search", difficulty: "Medium", platform: "LeetCode" },
  { title: "Capacity To Ship Packages Within D Days", url: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/", category: "Binary Search", difficulty: "Medium", platform: "LeetCode" },
  { title: "Minimum Limit Of Balls In A Bag", url: "https://leetcode.com/problems/minimum-limit-of-balls-in-a-bag/", category: "Binary Search", difficulty: "Medium", platform: "LeetCode" },
  { title: "Median Of Two Sorted Arrays", url: "https://leetcode.com/problems/median-of-two-sorted-arrays/", category: "Binary Search", difficulty: "Hard", platform: "LeetCode" },
  { title: "Count Of Smaller Numbers After Self", url: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/", category: "Binary Search", difficulty: "Hard", platform: "LeetCode" },
  { title: "Max Sum Of Rectangle No Larger Than K", url: "https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/", category: "Binary Search", difficulty: "Hard", platform: "LeetCode" },
  { title: "Split Array Largest Sum", url: "https://leetcode.com/problems/split-array-largest-sum/", category: "Binary Search", difficulty: "Hard", platform: "LeetCode" },
  { title: "Shortest Subarray With Sum At Least K", url: "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/", category: "Binary Search", difficulty: "Hard", platform: "LeetCode" },

  // ---- BFS ----
  { title: "Number Of Islands", url: "https://leetcode.com/problems/number-of-islands/", category: "BFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Rotting Oranges", url: "https://leetcode.com/problems/rotting-oranges/", category: "BFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Snakes And Ladders", url: "https://leetcode.com/problems/snakes-and-ladders/", category: "BFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Is Graph Bipartite", url: "https://leetcode.com/problems/is-graph-bipartite/", category: "BFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Minimum Jumps To Reach Home", url: "https://leetcode.com/problems/minimum-jumps-to-reach-home/", category: "BFS", difficulty: "Medium", platform: "LeetCode" },
  { title: "Word Ladder", url: "https://leetcode.com/problems/word-ladder/", category: "BFS", difficulty: "Hard", platform: "LeetCode" },
  { title: "Word Ladder II", url: "https://leetcode.com/problems/word-ladder-ii/", category: "BFS", difficulty: "Hard", platform: "LeetCode" },
  { title: "Cut Off Trees For Golf Event", url: "https://leetcode.com/problems/cut-off-trees-for-golf-event/", category: "BFS", difficulty: "Hard", platform: "LeetCode" },
  { title: "Reachable Nodes In Subdivided Graph", url: "https://leetcode.com/problems/reachable-nodes-in-subdivided-graph/", category: "BFS", difficulty: "Hard", platform: "LeetCode" },

  // ---- TWO POINTER ----
  { title: "Partition Labels", url: "https://leetcode.com/problems/partition-labels/", category: "Two Pointer", difficulty: "Medium", platform: "LeetCode" },
  { title: "Sort Colors", url: "https://leetcode.com/problems/sort-colors/", category: "Two Pointer", difficulty: "Medium", platform: "LeetCode" },
  { title: "Longest Repeating Character Replacement", url: "https://leetcode.com/problems/longest-repeating-character-replacement/", category: "Two Pointer", difficulty: "Medium", platform: "LeetCode" },
  { title: "Maximum Number Of Visible Points", url: "https://leetcode.com/problems/maximum-number-of-visible-points/", category: "Two Pointer", difficulty: "Hard", platform: "LeetCode" },
  { title: "Subarrays With K Different Integers", url: "https://leetcode.com/problems/subarrays-with-k-different-integers/", category: "Two Pointer", difficulty: "Hard", platform: "LeetCode" },

  // ---- STACK ----
  { title: "Min Stack", url: "https://leetcode.com/problems/min-stack/", category: "Stack", difficulty: "Easy", platform: "LeetCode" },
  { title: "Next Greater Element I", url: "https://leetcode.com/problems/next-greater-element-i/", category: "Stack", difficulty: "Easy", platform: "LeetCode" },
  { title: "Backspace String Compare", url: "https://leetcode.com/problems/backspace-string-compare/", category: "Stack", difficulty: "Easy", platform: "LeetCode" },
  { title: "Implement Queue Using Stacks", url: "https://leetcode.com/problems/implement-queue-using-stacks/", category: "Stack", difficulty: "Easy", platform: "LeetCode" },
  { title: "Implement Stack Using Queues", url: "https://leetcode.com/problems/implement-stack-using-queues/", category: "Stack", difficulty: "Easy", platform: "LeetCode" },
  { title: "Remove All Adjacent Duplicates In String II", url: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/", category: "Stack", difficulty: "Medium", platform: "LeetCode" },
  { title: "Daily Temperatures", url: "https://leetcode.com/problems/daily-temperatures/", category: "Stack", difficulty: "Medium", platform: "LeetCode" },
  { title: "Flatten Nested List Iterator", url: "https://leetcode.com/problems/flatten-nested-list-iterator/", category: "Stack", difficulty: "Medium", platform: "LeetCode" },
  { title: "Online Stock Span", url: "https://leetcode.com/problems/online-stock-span/", category: "Stack", difficulty: "Medium", platform: "LeetCode" },
  { title: "Minimum Cost Tree From Leaf Values", url: "https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/", category: "Stack", difficulty: "Medium", platform: "LeetCode" },
  { title: "Sum Of Subarray Minimums", url: "https://leetcode.com/problems/sum-of-subarray-minimums/", category: "Stack", difficulty: "Medium", platform: "LeetCode" },
  { title: "Evaluate Reverse Polish Notation", url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/", category: "Stack", difficulty: "Medium", platform: "LeetCode" },

  // ---- GRAPH ----
  { title: "Employee Importance", url: "https://leetcode.com/problems/employee-importance/", category: "Graph", difficulty: "Easy", platform: "LeetCode" },
  { title: "Find The Town Judge", url: "https://leetcode.com/problems/find-the-town-judge/", category: "Graph", difficulty: "Easy", platform: "LeetCode" },
  { title: "Evaluate Division", url: "https://leetcode.com/problems/evaluate-division/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Accounts Merge", url: "https://leetcode.com/problems/accounts-merge/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Network Delay Time", url: "https://leetcode.com/problems/network-delay-time/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Find Eventual Safe States", url: "https://leetcode.com/problems/find-eventual-safe-states/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Keys And Rooms", url: "https://leetcode.com/problems/keys-and-rooms/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Possible Bipartition", url: "https://leetcode.com/problems/possible-bipartition/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Most Stones Removed With Same Row Or Column", url: "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Regions Cut By Slashes", url: "https://leetcode.com/problems/regions-cut-by-slashes/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Satisfiability Of Equality Equations", url: "https://leetcode.com/problems/satisfiability-of-equality-equations/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "As Far From Land As Possible", url: "https://leetcode.com/problems/as-far-from-land-as-possible/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Number Of Closed Islands", url: "https://leetcode.com/problems/number-of-closed-islands/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Number Of Operations To Make Network Connected", url: "https://leetcode.com/problems/number-of-operations-to-make-network-connected/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Find The City With The Smallest Number Of Neighbors At A Threshold Distance", url: "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },
  { title: "Time Needed To Inform All Employees", url: "https://leetcode.com/problems/time-needed-to-inform-all-employees/", category: "Graph", difficulty: "Medium", platform: "LeetCode" },

  // ---- LINKED LIST ----
  { title: "Delete Node In A Linked List", url: "https://leetcode.com/problems/delete-node-in-a-linked-list/", category: "Linked List", difficulty: "Medium", platform: "LeetCode" },
  { title: "Middle Of The Linked List", url: "https://leetcode.com/problems/middle-of-the-linked-list/", category: "Linked List", difficulty: "Easy", platform: "LeetCode" },
  { title: "Convert Binary Number In A Linked List To Integer", url: "https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/", category: "Linked List", difficulty: "Easy", platform: "LeetCode" },
  { title: "Design Hashset", url: "https://leetcode.com/problems/design-hashset/", category: "Linked List", difficulty: "Easy", platform: "LeetCode" },
  { title: "Design Hashmap", url: "https://leetcode.com/problems/design-hashmap/", category: "Linked List", difficulty: "Easy", platform: "LeetCode" },
  { title: "Reverse Linked List", url: "https://leetcode.com/problems/reverse-linked-list/", category: "Linked List", difficulty: "Easy", platform: "LeetCode" },
  { title: "Reverse Nodes In K Group", url: "https://leetcode.com/problems/reverse-nodes-in-k-group/", category: "Linked List", difficulty: "Hard", platform: "LeetCode" },
  { title: "Merge Two Sorted Lists", url: "https://leetcode.com/problems/merge-two-sorted-lists/", category: "Linked List", difficulty: "Easy", platform: "LeetCode" },
  { title: "Merge K Sorted Lists", url: "https://leetcode.com/problems/merge-k-sorted-lists/", category: "Linked List", difficulty: "Hard", platform: "LeetCode" },
  { title: "Remove Duplicates From Sorted List", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-list/", category: "Linked List", difficulty: "Easy", platform: "LeetCode" },
  { title: "Linked List Cycle", url: "https://leetcode.com/problems/linked-list-cycle/", category: "Linked List", difficulty: "Easy", platform: "LeetCode" },
  { title: "Linked List Cycle II", url: "https://leetcode.com/problems/linked-list-cycle-ii/", category: "Linked List", difficulty: "Medium", platform: "LeetCode" },
  { title: "Intersection Of Two Linked Lists", url: "https://leetcode.com/problems/intersection-of-two-linked-lists/", category: "Linked List", difficulty: "Easy", platform: "LeetCode" },
  { title: "Palindrome Linked List", url: "https://leetcode.com/problems/palindrome-linked-list/", category: "Linked List", difficulty: "Easy", platform: "LeetCode" },
  { title: "Remove Linked List Elements", url: "https://leetcode.com/problems/remove-linked-list-elements/", category: "Linked List", difficulty: "Easy", platform: "LeetCode" },
  { title: "Design Browser History", url: "https://leetcode.com/problems/design-browser-history/", category: "Linked List", difficulty: "Medium", platform: "LeetCode" },
  { title: "LRU Cache", url: "https://leetcode.com/problems/lru-cache/", category: "Linked List", difficulty: "Medium", platform: "LeetCode" },
  { title: "Copy List With Random Pointer", url: "https://leetcode.com/problems/copy-list-with-random-pointer/", category: "Linked List", difficulty: "Medium", platform: "LeetCode" },

  // ---- HEAP ----
  { title: "K Closest Points To Origin", url: "https://leetcode.com/problems/k-closest-points-to-origin/", category: "Heap", difficulty: "Medium", platform: "LeetCode" },
  { title: "Kth Largest Element In An Array", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/", category: "Heap", difficulty: "Medium", platform: "LeetCode" },
  { title: "Reorganize String", url: "https://leetcode.com/problems/reorganize-string/", category: "Heap", difficulty: "Medium", platform: "LeetCode" },
  { title: "Furthest Building You Can Reach", url: "https://leetcode.com/problems/furthest-building-you-can-reach/", category: "Heap", difficulty: "Medium", platform: "LeetCode" },
  { title: "Kth Smallest Element In A Sorted Matrix", url: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/", category: "Heap", difficulty: "Medium", platform: "LeetCode" },
  { title: "Cheapest Flights Within K Stops", url: "https://leetcode.com/problems/cheapest-flights-within-k-stops/", category: "Heap", difficulty: "Medium", platform: "LeetCode" },
  { title: "Find The Most Competitive Subsequence", url: "https://leetcode.com/problems/find-the-most-competitive-subsequence/", category: "Heap", difficulty: "Medium", platform: "LeetCode" },
  { title: "Ugly Number II", url: "https://leetcode.com/problems/ugly-number-ii/", category: "Heap", difficulty: "Medium", platform: "LeetCode" },
  { title: "Merge K Sorted Lists", url: "https://leetcode.com/problems/merge-k-sorted-lists/", category: "Heap", difficulty: "Hard", platform: "LeetCode" },
  { title: "Sliding Window Maximum", url: "https://leetcode.com/problems/sliding-window-maximum/", category: "Heap", difficulty: "Hard", platform: "LeetCode" },
  { title: "The Skyline Problem", url: "https://leetcode.com/problems/the-skyline-problem/", category: "Heap", difficulty: "Hard", platform: "LeetCode" },
  { title: "Trapping Rain Water II", url: "https://leetcode.com/problems/trapping-rain-water-ii/", category: "Heap", difficulty: "Hard", platform: "LeetCode" },
  { title: "Minimum Number Of Refueling Stops", url: "https://leetcode.com/problems/minimum-number-of-refueling-stops/", category: "Heap", difficulty: "Hard", platform: "LeetCode" },
  { title: "Swim In Rising Water", url: "https://leetcode.com/problems/swim-in-rising-water/", category: "Heap", difficulty: "Hard", platform: "LeetCode" },
  { title: "Shortest Path To Get All Keys", url: "https://leetcode.com/problems/shortest-path-to-get-all-keys/", category: "Heap", difficulty: "Hard", platform: "LeetCode" },
  { title: "Minimum Cost To Hire K Workers", url: "https://leetcode.com/problems/minimum-cost-to-hire-k-workers/", category: "Heap", difficulty: "Hard", platform: "LeetCode" },
  { title: "K Th Smallest Prime Fraction", url: "https://leetcode.com/problems/k-th-smallest-prime-fraction/", category: "Heap", difficulty: "Hard", platform: "LeetCode" },

  // ---- SLIDING WINDOW ----
  { title: "Longest Substring With At Least K Repeating Characters", url: "https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters/", category: "Sliding Window", difficulty: "Medium", platform: "LeetCode" },
  { title: "Max Consecutive Ones III", url: "https://leetcode.com/problems/max-consecutive-ones-iii/", category: "Sliding Window", difficulty: "Medium", platform: "LeetCode" },
  { title: "Grumpy Bookstore Owner", url: "https://leetcode.com/problems/grumpy-bookstore-owner/", category: "Sliding Window", difficulty: "Medium", platform: "LeetCode" },
  { title: "Sliding Window Median", url: "https://leetcode.com/problems/sliding-window-median/", category: "Sliding Window", difficulty: "Hard", platform: "LeetCode" },
];
